### PR TITLE
Addressing #68

### PR DESCRIPTION
**Pull request by cjwilburn**
My IDE also seems to have gotten rid of whitespace. If that's a problem, let me know. Thanks!

### CODE REVIEW

**Comment by cjwilburn** [comment]
@laralib It looks a test failed for code not included in this PR. I think it's otherwise good to go.

**Comment by kneipp** [comment]
+1 some love with this PR

Trying to use this package with Laravel 5.4

**Comment by cjwilburn** [comment]
@kneipp this one addresses all of the files that need updating (three as opposed to the two in #70), but thanks for taking a look!

**Comment by cjwilburn** [comment]
@laralib this fork now passes both merge checks and is still otherwise compatible with Laravel 5.4.x

**Pull request merged**
